[package]
name = "ldpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
labrador-ldpc = "1.0.1"
clap = { version = "3.1.18", features = ["derive"] }
num = "0.4.0"
dpc-pariter = "0.5.1"
